package com.example.fitcore

object ExerciseData {

    private val allExercises = listOf(
        Exercise(1, "Press de Banca", "Pecho", "Barra", "Intermedio",
            "Acuéstate en el banco, agarra la barra con las manos a la anchura de los hombros. Baja el pecho hasta que los brazos formen 90° y empuja hacia arriba.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/barbell-bench-press.gif"),
        Exercise(2, "Press Inclinado con Mancuernas", "Pecho", "Mancuernas", "Intermedio",
            "En banco inclinado a 30°, presiona las mancuernas desde el pecho hasta extender los brazos. Controla el descenso.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-incline-bench-press.gif"),
        Exercise(3, "Aperturas con Mancuernas", "Pecho", "Mancuernas", "Principiante",
            "Acuéstate, abre los brazos con mancuernas hasta sentir estiramiento en el pecho, luego cierra los brazos como abrazando un árbol.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-fly.gif"),
        Exercise(4, "Cruces en Polea", "Pecho", "Polea", "Intermedio",
            "De pie entre las poleas, cruza las manos frente al pecho contrayendo los pectorales. Mantén la posición un segundo.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/cable-standing-up-straight-crossovers.gif"),
        Exercise(5, "Fondos en Paralelas", "Pecho", "Peso corporal", "Avanzado",
            "Apóyate en las barras paralelas, baja flexionando los codos hasta 90° inclinando el torso hacia adelante, y sube empujando.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/chest-dip.gif"),
        Exercise(31, "Press de Banca con Mancuernas", "Pecho", "Mancuernas", "Principiante",
            "Acuéstate en el banco con mancuernas a la altura del pecho. Empuja hacia arriba hasta extender los brazos. Baja controlado.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-bench-press.gif"),
        Exercise(32, "Press Declinado con Barra", "Pecho", "Barra", "Intermedio",
            "En banco declinado, baja la barra al pecho inferior y presiona hacia arriba. Enfócate en la porción inferior del pecho.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/barbell-decline-bench-press.gif"),
        Exercise(33, "Pullover con Mancuerna", "Pecho", "Mancuernas", "Intermedio",
            "Acuéstate transversalmente en el banco, sostén una mancuerna con ambas manos y llévala detrás de la cabeza. Regresa contrayendo el pecho.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-pullover.gif"),
        Exercise(34, "Aperturas Inclinadas con Mancuernas", "Pecho", "Mancuernas", "Intermedio",
            "En banco inclinado, abre los brazos con mancuernas manteniendo los codos ligeramente flexionados. Cierra contrayendo el pecho superior.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-incline-fly.gif"),
        Exercise(35, "Press en Polea", "Pecho", "Polea", "Intermedio",
            "Agarra las poleas y presiona hacia adelante como si hicieras press de banca de pie. Contrae el pecho al final del movimiento.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/cable-bench-press.gif"),
        Exercise(36, "Flexiones de Pecho", "Pecho", "Peso corporal", "Principiante",
            "En posición de plancha con manos abiertas, baja el pecho al suelo flexionando los codos y empuja hacia arriba.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/push-up.gif"),
        Exercise(37, "Contractora de Pecho", "Pecho", "Máquina", "Principiante",
            "Sentado en la máquina, junta los brazos frente al pecho contrayendo los pectorales. Regresa lento.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/lever-chest-press.gif"),
        Exercise(38, "Aperturas Declinadas con Mancuernas", "Pecho", "Mancuernas", "Avanzado",
            "En banco declinado, abre y cierra los brazos con mancuernas trabajando la porción inferior del pecho.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/dumbbell-decline-fly.gif"),
        Exercise(39, "Cable Cruzado Bajo", "Pecho", "Polea", "Intermedio",
            "Agarra las poleas desde la posición más baja y cruza las manos hacia arriba frente al pecho. Trabaja el pecho superior.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/cable-low-fly.gif"),
        Exercise(40, "Flexiones Declinadas", "Pecho", "Peso corporal", "Intermedio",
            "Con los pies elevados en un banco, baja el pecho al suelo. Mayor énfasis en el pecho superior.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/decline-push-up.gif"),
        Exercise(41, "Contractora Inclinada", "Pecho", "Máquina", "Intermedio",
            "En la máquina de contractora inclinada, junta los brazos hacia arriba y adelante. Aísla el pecho superior.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/lever-incline-chest-press.gif"),
        Exercise(42, "Apertura en Polea Alta", "Pecho", "Polea", "Avanzado",
            "Desde poleas altas, baja las manos en arco hasta juntarlas frente a los muslos. Trabaja el pecho inferior.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/cable-incline-fly.gif"),
        Exercise(43, "Press de Banca con Agarre Ancho", "Pecho", "Barra", "Intermedio",
            "Agarra la barra más ancho que los hombros. Baja al pecho y presiona. Enfatiza la parte externa del pectoral.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/barbell-wide-bench-press.gif"),
        Exercise(44, "Flexiones con Aplauso", "Pecho", "Peso corporal", "Avanzado",
            "Impúlsate hacia arriba con fuerza para despegar las manos del suelo y aplaudir en el aire. Ejercicio pliométrico.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/clap-push-up.gif"),
        Exercise(45, "Fondos Lastrados", "Pecho", "Peso corporal", "Avanzado",
            "Fondos en paralelas con peso adicional mediante cinturón. Baja hasta 90° y sube con potencia.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/pectorals/weighted-straight-bar-dip.gif"),

        Exercise(6, "Dominadas", "Espalda", "Barra", "Intermedio",
            "Cuélgate de la barra con agarre prono (palmas al frente). Tira del cuerpo hacia arriba hasta que la barbilla supere la barra.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/pull-up.gif"),
        Exercise(7, "Remo con Barra", "Espalda", "Barra", "Intermedio",
            "Inclina el torso hacia adelante con la espalda recta, tira de la barra hacia el abdomen contrayendo los dorsales.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-seated-high-row-v-bar.gif"),
        Exercise(8, "Remo con Mancuerna", "Espalda", "Mancuernas", "Principiante",
            "Apoya una rodilla y mano en el banco. Tira de la mancuerna hacia la cadera apretando la espalda.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-one-arm-pulldown.gif"),
        Exercise(9, "Jalón al Pecho", "Espalda", "Polea", "Principiante",
            "Sentado en la máquina, jalón de la barra alta hacia el pecho apretando los dorsales. No te inclines hacia atrás.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-pulldown.gif"),
        Exercise(10, "Peso Muerto Rumano", "Espalda", "Barra", "Avanzado",
            "De pie, baja la barra por las piernas manteniendo la espalda recta hasta sentir el estiramiento en isquiotibiales.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/barbell-straight-leg-deadlift.gif"),
        Exercise(46, "Remo en Polea Baja", "Espalda", "Polea", "Intermedio",
            "Sentado en la polea baja, tira del asa hacia el abdomen manteniendo la espalda recta. Contrae los dorsales al final.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-thibaudeau-kayak-row.gif"),
        Exercise(47, "Jalón al Pecho Agarre Inverso", "Espalda", "Polea", "Intermedio",
            "Con agarre supino (palmas hacia ti), jala la barra al pecho. Mayor activación de dorsales inferiores.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-underhand-pulldown.gif"),
        Exercise(48, "Dominadas con Agarre Cerrado", "Espalda", "Barra", "Intermedio",
            "Con las manos juntas en agarre neutro, tira del cuerpo hacia arriba. Trabaja la parte media de la espalda.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/close-grip-chin-up.gif"),
        Exercise(49, "Dominadas Lastradas", "Espalda", "Barra", "Avanzado",
            "Dominadas con peso adicional mediante cinturón. Ejercicio de máxima intensidad para dorsal ancho.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/weighted-pull-up.gif"),
        Exercise(50, "Dominadas con Agarre Ancho", "Espalda", "Barra", "Intermedio",
            "Agarre prono con manos muy separadas. Tira del pecho a la barra. Máxima apertura del dorsal ancho.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/wide-grip-pull-up.gif"),
        Exercise(51, "Jalón Tras Nuca", "Espalda", "Polea", "Intermedio",
            "Jala la barra detrás de la cabeza hasta la nuca. Cuidado con la cervical, usa peso moderado.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-rear-pulldown.gif"),
        Exercise(52, "Dominadas Asistidas", "Espalda", "Barra", "Principiante",
            "Usa una banda elástica o máquina de asistencia para ayudarte en el movimiento. Progresivamente reduce la ayuda.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/assisted-pull-up.gif"),
        Exercise(53, "Pullover con Barra", "Espalda", "Barra", "Intermedio",
            "Acuéstate en el banco, sostén la barra sobre el pecho y llévala detrás de la cabeza. Estira y contrae los dorsales.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/barbell-pullover.gif"),
        Exercise(54, "Polea Recta con Brazos Extendidos", "Espalda", "Polea", "Intermedio",
            "De pie, jala la barra recta hacia los muslos manteniendo los brazos extendidos. Aísla los dorsales.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-straight-arm-pulldown.gif"),
        Exercise(55, "Dominadas Agarre Neutro", "Espalda", "Barra", "Intermedio",
            "Con las palmas enfrentadas en barras paralelas, tira del cuerpo hacia arriba. Menos estrés en muñecas.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/pull-up-neutral-grip.gif"),
        Exercise(56, "Muscle Up", "Espalda", "Barra", "Avanzado",
            "Combinación de dominada y fondos. Tira con potencia para pasar el pecho sobre la barra y luego empuja hacia arriba.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/muscle-up.gif"),
        Exercise(57, "Remo con Giro en Polea", "Espalda", "Polea", "Avanzado",
            "De pie, jala la polea baja con una mano y gira el torso. Trabaja dorsales y oblicuos de forma dinámica.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-twisting-pull.gif"),
        Exercise(58, "Jalón al Pecho Agarre Prono", "Espalda", "Polea", "Principiante",
            "Agarre prono abierto, jala la barra al pecho superior mientras inclinas ligeramente el torso atrás.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/cable-lat-pulldown-full-range-of-motion.gif"),
        Exercise(59, "Dominadas Mixtas", "Espalda", "Barra", "Intermedio",
            "Una mano en prono y otra en supino. Alterna en cada serie para un desarrollo equilibrado.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/mixed-grip-chin-up.gif"),
        Exercise(60, "Dominadas Supinas", "Espalda", "Barra", "Intermedio",
            "Agarre supino (palmas hacia ti), tira del cuerpo hacia arriba. Mayor activación de bíceps y dorsales bajos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/lats/reverse-grip-pull-up.gif"),

        Exercise(11, "Sentadilla con Barra", "Piernas", "Barra", "Intermedio",
            "Con la barra en los trapecios, baja como si te sentaras hasta que los muslos estén paralelos al suelo o más.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/barbell-bench-squat.gif"),
        Exercise(12, "Prensa de Piernas", "Piernas", "Máquina", "Principiante",
            "Sentado en la máquina, empuja la plataforma extendiendo las piernas sin bloquear las rodillas.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/lever-alternate-leg-press.gif"),
        Exercise(13, "Curl Femoral", "Piernas", "Máquina", "Principiante",
            "Acuéstate boca abajo en la máquina, flexiona las rodillas levantando el peso controladamente.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/lever-lying-leg-curl.gif"),
        Exercise(14, "Extensión de Cuádriceps", "Piernas", "Máquina", "Principiante",
            "Sentado en la máquina, extiende las rodillas hasta las piernas queden rectas y contrae los cuádriceps.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/lever-leg-extension.gif"),
        Exercise(15, "Zancadas con Mancuernas", "Piernas", "Mancuernas", "Intermedio",
            "Da un paso largo hacia adelante con mancuernas y baja la rodilla trasera casi al suelo. Alterna piernas.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/dumbbell-step-up-lunge.gif"),
        Exercise(61, "Sentadilla Goblet", "Piernas", "Mancuernas", "Principiante",
            "Sostén una mancuerna contra el pecho con ambas manos. Baja en sentadilla manteniendo el torso erguido.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/dumbbell-goblet-squat.gif"),
        Exercise(62, "Buenos Días", "Piernas", "Barra", "Intermedio",
            "Con la barra en los trapecios, inclina el torso hacia adelante manteniendo la espalda recta. Trabaja isquiotibiales y espalda baja.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/barbell-good-morning.gif"),
        Exercise(63, "Split Squat con Barra", "Piernas", "Barra", "Intermedio",
            "Con un pie adelantado y la barra en los trapecios, baja hasta que la rodilla trasera toque el suelo.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/barbell-split-squat-v-2.gif"),
        Exercise(64, "Curl Femoral Sentado", "Piernas", "Máquina", "Principiante",
            "Sentado en la máquina, flexiona las piernas contra la resistencia. Trabaja los isquiotibiales de forma aislada.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/lever-seated-leg-curl.gif"),
        Exercise(65, "Peso Muerto a Una Pierna", "Piernas", "Mancuernas", "Intermedio",
            "Sostén una mancuerna y eleva una pierna hacia atrás. Baja el torso manteniendo el equilibrio. Trabaja isquiotibiales y glúteos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/single-leg-platform-slide.gif"),
        Exercise(66, "Sentadilla Ancha", "Piernas", "Barra", "Intermedio",
            "Con los pies más separados que el ancho de hombros, baja en sentadilla. Mayor énfasis en aductores y glúteos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/barbell-wide-squat.gif"),
        Exercise(67, "Glute Ham Raise", "Piernas", "Peso corporal", "Avanzado",
            "Con los pies asegurados, baja el torso controladamente y sube contrayendo isquiotibiales y glúteos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/glute-ham-raise.gif"),
        Exercise(68, "Sentadilla Búlgara con Mancuerna", "Piernas", "Mancuernas", "Intermedio",
            "Con un pie en el banco detrás, baja en sentadilla con mancuernas. Trabaja cuádriceps y glúteos unilateralmente.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/dumbbell-single-leg-split-squat.gif"),
        Exercise(69, "Sentadilla Overhead", "Piernas", "Barra", "Avanzado",
            "Sostén la barra sobre la cabeza con brazos extendidos y baja en sentadilla. Requiere gran movilidad y estabilidad.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/barbell-overhead-squat.gif"),
        Exercise(70, "Clean and Press", "Piernas", "Barra", "Avanzado",
            "Levanta la barra desde el suelo hasta los hombros y luego presiona sobre la cabeza. Movimiento explosivo de cuerpo completo.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/barbell-clean-and-press.gif"),
        Exercise(71, "Split Búlgaro con Mancuernas", "Piernas", "Mancuernas", "Intermedio",
            "Pie trasero elevado en un banco, baja en sentadilla con mancuernas. Mayor rango de movimiento y activación de glúteos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/dumbbell-step-up-split-squat.gif"),
        Exercise(72, "Curl Femoral de Pie", "Piernas", "Máquina", "Principiante",
            "De pie en la máquina, flexiona una pierna hacia atrás llevando el talón al glúteo. Trabaja isquiotibiales unilateralmente.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/hamstrings/standing-single-leg-curl.gif"),
        Exercise(73, "Sentadilla en Bosu", "Piernas", "Peso corporal", "Intermedio",
            "Sobre una superficie inestable, realiza sentadillas. Mejora el equilibrio y la propiocepción.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/squat-on-bosu-ball.gif"),
        Exercise(74, "Zancada Inversa con Barra", "Piernas", "Barra", "Intermedio",
            "Con la barra en los trapecios, da un paso hacia atrás y baja la rodilla. Alterna piernas.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/barbell-squat-jump-step-rear-lunge.gif"),
        Exercise(75, "Farmer Walks", "Piernas", "Mancuernas", "Principiante",
            "Camina sosteniendo mancuernas pesadas a los lados. Mejora la resistencia muscular y el agarre.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/quads/farmers-walk.gif"),

        Exercise(16, "Press Militar", "Hombros", "Barra", "Intermedio",
            "De pie, presiona la barra desde los hombros hasta extender los brazos sobre la cabeza. Core firme.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/barbell-standing-wide-military-press.gif"),
        Exercise(17, "Elevaciones Laterales", "Hombros", "Mancuernas", "Principiante",
            "De pie, eleva las mancuernas a los lados hasta la altura de los hombros con los codos ligeramente flexionados.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-lateral-raise.gif"),
        Exercise(18, "Elevaciones Frontales", "Hombros", "Mancuernas", "Principiante",
            "Eleva las mancuernas frente al cuerpo hasta la altura de los hombros. Alterna los brazos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-front-raise.gif"),
        Exercise(19, "Pájaros", "Hombros", "Mancuernas", "Intermedio",
            "Inclina el torso hacia adelante, eleva las mancuernas a los lados contrayendo los trapecios posteriores.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-rear-delt-row-shoulder.gif"),
        Exercise(20, "Arnold Press", "Hombros", "Mancuernas", "Intermedio",
            "Sentado, presiona las mancuernas desde frente (palmas hacia ti) rotando hasta arriba (palmas al frente).",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-arnold-press.gif"),
        Exercise(76, "Press de Hombros Sentado con Mancuernas", "Hombros", "Mancuernas", "Intermedio",
            "Sentado en un banco con respaldo, presiona las mancuernas desde los hombros hasta extender los brazos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-seated-shoulder-press.gif"),
        Exercise(77, "Elevaciones Posteriores en Máquina", "Hombros", "Máquina", "Principiante",
            "Sentado en la máquina, abre los brazos hacia atrás contrayendo los deltoides posteriores.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/lever-seated-reverse-fly.gif"),
        Exercise(78, "Press Tras Nuca con Barra", "Hombros", "Barra", "Avanzado",
            "Sentado, baja la barra detrás de la cabeza hasta la nuca y presiona hacia arriba. Requiere buena movilidad.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/barbell-seated-behind-head-military-press.gif"),
        Exercise(79, "Elevaciones Laterales en Polea", "Hombros", "Polea", "Intermedio",
            "De pie, eleva el brazo hacia el lado jalando la polea baja. Trabaja el deltoide lateral con tensión constante.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/cable-lateral-raise.gif"),
        Exercise(80, "Face Pull", "Hombros", "Polea", "Intermedio",
            "Jala la polea hacia la cara con las manos separadas. Trabaja deltoides posteriores y rotadores externos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/cable-standing-rear-delt-row-with-rope.gif"),
        Exercise(81, "Press Arnold Variante Sentado", "Hombros", "Mancuernas", "Intermedio",
            "Similar al Arnold Press pero con las palmas hacia el cuerpo al inicio. Rotación completa del hombro.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-arnold-press-v-2.gif"),
        Exercise(82, "Elevación Frontal con Barra", "Hombros", "Barra", "Principiante",
            "De pie, eleva la barra frente al cuerpo hasta la altura de los hombros manteniendo los brazos extendidos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/barbell-front-raise.gif"),
        Exercise(83, "Press de Hombros en Máquina", "Hombros", "Máquina", "Principiante",
            "Sentado en la máquina, presiona los brazos hacia arriba. Movimiento guiado ideal para principiantes.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/lever-shoulder-press.gif"),
        Exercise(84, "Pájaro en Polea", "Hombros", "Polea", "Intermedio",
            "De pie, jala las poleas cruzadas hacia los lados con los brazos extendidos. Trabaja deltoides posteriores.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/cable-rear-delt-row-stirrups.gif"),
        Exercise(85, "Elevaciones Laterales Inclinadas", "Hombros", "Mancuernas", "Intermedio",
            "Inclinado hacia adelante en banco, eleva las mancuernas a los lados. Trabaja deltoides posteriores.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-incline-rear-lateral-raise.gif"),
        Exercise(86, "Press con Mancuerna a Una Mano", "Hombros", "Mancuernas", "Intermedio",
            "De pie, presiona una mancuerna sobre la cabeza. Trabaja cada hombro unilateralmente para corregir desequilibrios.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-one-arm-shoulder-press.gif"),
        Exercise(87, "Remo al Mentón con Barra", "Hombros", "Barra", "Intermedio",
            "De pie, eleva la barra hasta el mentón guiando con los codos. Trabaja deltoides y trapecios.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/barbell-upright-row.gif"),
        Exercise(88, "Elevación en Y", "Hombros", "Peso corporal", "Principiante",
            "Acuéstate boca abajo, eleva los brazos en forma de Y. Activa los deltoides posteriores sin peso.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/band-y-raise.gif"),
        Exercise(89, "Push Press", "Hombros", "Mancuernas", "Avanzado",
            "Con mancuernas, flexiona ligeramente las rodillas y usa el impulso para presionar sobre la cabeza.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-push-press.gif"),
        Exercise(90, "Cuban Press", "Hombros", "Mancuernas", "Avanzado",
            "Eleva las mancuernas frente al cuerpo, rota los hombros hacia afuera y luego presiona hacia arriba. Trabajo de manguito rotador.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/delts/dumbbell-cuban-press.gif"),

        Exercise(21, "Curl de Bíceps con Barra", "Brazos", "Barra", "Principiante",
            "De pie, flexiona los codos levantando la barra contrayendo los bíceps. No balancees el cuerpo.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/barbell-curl.gif"),
        Exercise(22, "Curl Martillo", "Brazos", "Mancuernas", "Principiante",
            "Con palmas enfrentadas, flexiona los codos levantando las mancuernas. Trabaja braquial y braquiorradial.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-hammer-curl.gif"),
        Exercise(23, "Curl Concentrado", "Brazos", "Mancuernas", "Principiante",
            "Sentado, apoya el codo en el muslo y flexiona el brazo con la mancuerna lentamente.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-concentration-curl.gif"),
        Exercise(24, "Extensión de Tríceps en Polea", "Brazos", "Polea", "Principiante",
            "De pie, extiende los brazos empujando la barra hacia abajo contrayendo los tríceps. Codos fijos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-pushdown.gif"),
        Exercise(25, "Press Francés", "Brazos", "Barra", "Intermedio",
            "Acuéstate, baja la barra hacia la frente flexionando solo los codos. Extiende sin mover los hombros.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/barbell-lying-triceps-extension-skull-crusher.gif"),
        Exercise(91, "Curl con Barra Z", "Brazos", "Barra", "Principiante",
            "Con barra Z, flexiona los codos levantando el peso contrayendo los bíceps. La barra Z reduce la tensión en las muñecas.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/ez-barbell-curl.gif"),
        Exercise(92, "Curl Alterno con Mancuernas", "Brazos", "Mancuernas", "Principiante",
            "De pie, alterna flexionando cada brazo llevando la mancuerna al hombro. Supina la mano al subir.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-alternate-biceps-curl.gif"),
        Exercise(93, "Curl en Polea Baja", "Brazos", "Polea", "Principiante",
            "De pie frente a la polea baja, flexiona los codos llevando las asas a los hombros. Tensión constante en el bíceps.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/cable-curl.gif"),
        Exercise(94, "Curl Inclinado con Mancuernas", "Brazos", "Mancuernas", "Intermedio",
            "En banco inclinado, deja caer los brazos y flexiona los codos. Mayor estiramiento y contracción del bíceps.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-incline-curl.gif"),
        Exercise(95, "Curl Predicador con Barra Z", "Brazos", "Barra", "Intermedio",
            "Apoya los brazos en el banco predicador con barra Z y flexiona los codos. Aísla el bíceps eliminando impulso.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/ez-barbell-close-grip-preacher-curl.gif"),
        Exercise(96, "Curl en Polea Alta", "Brazos", "Polea", "Intermedio",
            "De pie bajo la polea alta, flexiona los codos llevando las manos a la cabeza. Trabaja la porción larga del bíceps.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/cable-overhead-curl.gif"),
        Exercise(97, "Curl Scott con Mancuerna", "Brazos", "Mancuernas", "Intermedio",
            "Apoya el brazo en el banco Scott y flexiona el codo con la mancuerna. Máximo aislamiento del bíceps.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/biceps/dumbbell-preacher-curl.gif"),
        Exercise(98, "Fondos de Tríceps", "Brazos", "Peso corporal", "Intermedio",
            "Apoya las manos en un banco detrás de ti, baja el cuerpo flexionando los codos y vuelve a subir.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/triceps-dip.gif"),
        Exercise(99, "Extensión de Tríceps sobre Cabeza", "Brazos", "Mancuernas", "Intermedio",
            "Sentado con una mancuerna sobre la cabeza, baja detrás de la cabeza flexionando el codo y extiende.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/dumbbell-seated-triceps-extension.gif"),
        Exercise(100, "Press de Banca con Agarre Cerrado", "Brazos", "Barra", "Intermedio",
            "Acuéstate en el banco con las manos juntas en la barra. Baja al pecho y presiona. Trabaja tríceps intensamente.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/barbell-close-grip-bench-press.gif"),
        Exercise(101, "Patada de Tríceps", "Brazos", "Mancuernas", "Principiante",
            "Inclina el torso, brazo paralelo al suelo, extiende el antebrazo hacia atrás contrayendo el tríceps.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/dumbbell-kickback.gif"),
        Exercise(102, "Extensión de Tríceps en Polea Alta", "Brazos", "Polea", "Intermedio",
            "De pie bajo la polea alta con soga, jala hacia abajo y separa las manos al final. Máxima contracción del tríceps.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/cable-overhead-triceps-extension-rope-attachment.gif"),
        Exercise(103, "Tríceps en Máquina", "Brazos", "Máquina", "Principiante",
            "Sentado en la máquina, extiende los antebrazos contra la resistencia. Movimiento guiado para aislar tríceps.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/lever-triceps-extension.gif"),
        Exercise(104, "Press Francés a Una Mano", "Brazos", "Mancuernas", "Intermedio",
            "Acuéstate y baja la mancuerna hacia el hombro opuesto flexionando el codo. Trabaja cada tríceps unilateralmente.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/dumbbell-one-arm-french-press-on-exercise-ball.gif"),
        Exercise(105, "Flexiones de Tríceps", "Brazos", "Peso corporal", "Intermedio",
            "Manos juntas en el suelo en posición de plancha, baja el pecho flexionando los codos pegados al cuerpo.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/triceps/close-grip-push-up.gif"),

        Exercise(26, "Crunch Abdominal", "Core", "Peso corporal", "Principiante",
            "Acuéstate boca arriba, flexiona el tronco llevando los hombros del suelo. Contrae el abdomen en cada repetición.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/crunch-floor.gif"),
        Exercise(27, "Plancha", "Core", "Peso corporal", "Principiante",
            "Apoya antebrazos y puntas de los pies, mantén el cuerpo recto como una tabla. Aguanta 30-60 segundos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/front-plank-with-twist.gif"),
        Exercise(28, "Mountain Climbers", "Core", "Peso corporal", "Intermedio",
            "En posición de plancha, alterna llevando las rodillas al pecho rápidamente como corriendo en el sitio.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/bridge-mountain-climber-cross-body.gif"),
        Exercise(29, "Russian Twists", "Core", "Peso corporal", "Intermedio",
            "Sentado con pies elevados y torso inclinado 45°, gira el torso tocando el suelo a cada lado.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/russian-twist.gif"),
        Exercise(30, "Elevación de Piernas", "Core", "Peso corporal", "Intermedio",
            "Acuéstate boca arriba, eleva las piernas rectas hasta 90° y baja controlado sin tocar el suelo.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/lying-leg-raise-flat-bench.gif"),
        Exercise(106, "Elevación de Rodillas Colgado", "Core", "Peso corporal", "Intermedio",
            "Cuélgate de una barra y eleva las rodillas al pecho contrayendo el abdomen. Baja controlado.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/hanging-leg-hip-raise.gif"),
        Exercise(107, "Crunch en Máquina", "Core", "Máquina", "Principiante",
            "Sentado en la máquina de abdominales, flexiona el tronco hacia adelante contrayendo el abdomen.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/lever-seated-crunch.gif"),
        Exercise(108, "Abdominales en Polea", "Core", "Polea", "Intermedio",
            "Arrodillado frente a la polea alta, jala hacia abajo flexionando el tronco. Contrae el abdomen profundamente.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/cable-kneeling-crunch.gif"),
        Exercise(109, "Bicicleta", "Core", "Peso corporal", "Intermedio",
            "Acuéstate y lleva el codo a la rodilla contraria alternando. Trabaja oblicuos y recto abdominal.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/air-bike.gif"),
        Exercise(110, "Plancha Lateral", "Core", "Peso corporal", "Intermedio",
            "Apóyate en un antebrazo y el costado del pie, mantén el cuerpo recto. Trabaja oblicuos profundos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/bodyweight-incline-side-plank.gif"),
        Exercise(111, "V-ups", "Core", "Peso corporal", "Avanzado",
            "Acuéstate y eleva piernas y torso simultáneamente formando una V. Toca los pies con las manos.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/v-sit-on-floor.gif"),
        Exercise(112, "Crunch Declinado", "Core", "Peso corporal", "Intermedio",
            "En banco declinado con pies asegurados, flexiona el tronco llevando el pecho a las rodillas.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/decline-crunch.gif"),
        Exercise(113, "Elevación de Piernas Colgado", "Core", "Peso corporal", "Avanzado",
            "Cuélgate de la barra y eleva las piernas rectas hasta paralelas al suelo. Controla el descenso.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/hanging-straight-leg-raise.gif"),
        Exercise(114, "Abdominales con Cable de Pie", "Core", "Polea", "Intermedio",
            "De pie frente a la polea alta, flexiona el tronco hacia abajo jalando la soga. Contrae el abdomen al bajar.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/cable-standing-crunch-with-rope-attachment.gif"),
        Exercise(115, "Rueda Abdominal", "Core", "Peso corporal", "Avanzado",
            "Arrodillado con la rueda en las manos, extiende el cuerpo hacia adelante y vuelve contrayendo el abdomen.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/wheel-rollerout.gif"),
        Exercise(116, "Crunch con Peso", "Core", "Peso corporal", "Intermedio",
            "Acuéstate con un disco sobre el pecho y realiza crunch. Mayor resistencia para hipertrofia abdominal.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/weighted-crunch.gif"),
        Exercise(117, "Plancha con Peso", "Core", "Peso corporal", "Avanzado",
            "En posición de plancha con un disco en la espalda, mantén la posición. Mayor exigencia para el core.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/weighted-front-plank.gif"),
        Exercise(118, "Abdominal en Máquina Contractora", "Core", "Máquina", "Principiante",
            "Sentado en la máquina, flexiona el tronco hacia adelante con el pecho apoyado en el pad.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/lever-seated-crunch-chest-pad.gif"),
        Exercise(119, "Giros Rusos con Peso", "Core", "Peso corporal", "Intermedio",
            "Con un disco, gira el torso a cada lado tocando el suelo. Trabaja oblicuos con resistencia adicional.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/weighted-russian-twist.gif"),
        Exercise(120, "Abdominal en V con Balón", "Core", "Peso corporal", "Intermedio",
            "Acuéstate, eleva piernas y torso simultáneamente llevando las manos a los pies. Mayor rango de movimiento.",
            "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/abs/jackknife-sit-up.gif")
    )

    fun getAll(): List<Exercise> = allExercises

    fun getById(id: Int): Exercise? = allExercises.find { it.id == id }

    fun getByMuscleGroup(group: String): List<Exercise> {
        if (group.equals("Todos", ignoreCase = true)) return allExercises
        return allExercises.filter { it.muscleGroup.equals(group, ignoreCase = true) }
    }

    fun search(query: String): List<Exercise> {
        val q = query.lowercase().trim()
        if (q.isEmpty()) return allExercises
        return allExercises.filter {
            it.name.lowercase().contains(q) ||
            it.muscleGroup.lowercase().contains(q) ||
            it.equipment.lowercase().contains(q) ||
            it.difficulty.lowercase().contains(q)
        }
    }

    fun getMuscleGroups(): List<String> = listOf("Todos", "Pecho", "Espalda", "Piernas", "Hombros", "Brazos", "Core")
}
